# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml



stages:
#  - test
  - build
  - deploy

# format:
#   stage: test
#   script:
#     - cd server
#     - go fmt $(go list ./... | grep -v /vendor/)
#     - go vet $(go list ./... | grep -v /vendor/)
#     - go test -race $(go list ./... | grep -v /vendor/)

compile-server:
  stage: build
  image: golang:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[\d]\.[\d]\.[\d]/
  script:
    - cd server
    - mkdir -p bin
    - go build -o bin ./...
  artifacts:
    paths:
      - server/bin

deploy-test:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[\d]\.[\d]\.[\d]-test[\d]$/
  environment:
    name: test server
    url: http://192.168.35.41:8080
  tags:
    - mhsm
    - test
  script:
    - scp -i ~/.ssh/myhelmsauer_deploy ./server/bin/server deployer@192.168.35.41:schadenmeldung
    - ssh -i  ~/.ssh/myhelmsauer_deploy deployer@192.168.35.41 "sudo /home/deployer/adm/update_schadenmelder"


  

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
