### Verträge
POST https://portalinterface.helmsauer-gruppe.de:4448/portalinterface/CustomerQuery.aspx HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Query=Vertraege
&Username=Demokunde
&Password=Demo90443HK
&AdressID=AD_201406170853335LI

### Vertrag
POST https://portalinterface.helmsauer-gruppe.de:4448/portalinterface/CustomerQuery.aspx HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Query=Vertrag
&Username=Demokunde
&Password=Demo90443HK
&AdressID=AD_201406170853335LI
&VertragsID=VER20140626092811P76

### Dokumente
POST https://portalinterface.helmsauer-gruppe.de:4448/portalinterface/CustomerQuery.aspx HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Query=Dokumente
&Username=Demokunde
&Password=Demo90443HK
&AdressID=AD_201406170853335LI
&VertragsID=VER20140626092811P76

### Dokument
POST https://portalinterface.helmsauer-gruppe.de:4448/portalinterface/CustomerQuery.aspx HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Query=Dokument
&Username=Demokunde
&Password=Demo90443HK
&AdressID=AD_201406170853335LI
&DokumentID=DOK20140703114017KSI
&DokTitle=BVK - Nachtrag Eigentumswechsel


### Adressen
POST https://portalinterface.helmsauer-gruppe.de:4448/portalinterface/CustomerQuery.aspx HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Query=Adressen
&Username=Demokunde
&Password=Demo90443HK

### Login
POST https://portalinterface.helmsauer-gruppe.de:4448/portalinterface/CustomerQuery.aspx HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Query=Login
&Username=Demokunde
&Password=Demo90443HK

### LoginInvalid
POST https://portalinterface.helmsauer-gruppe.de:4448/portalinterface/CustomerQuery.aspx HTTP/1.1
Content-Type: application/x-www-form-urlencoded

Query=Login
&Username=Demokunde
&Password=Demo90443HK!
