### login
POST https://schadenmeldung.helmsauer-gruppe.de/api/v1/login HTTP/1.1
content-type: application/json

{
    "user":"Demokunde",
    "password":"Demo90443HK",
    "gruppe":"hk"
}

### verträge
GET https://schadenmeldung.helmsauer-gruppe.de/api/v1/verträge HTTP/1.1
content-type: application/json
authorization: 699fcccc-3c34-465e-8922-b94fa7675edd

### login prod maxmustermann
POST https://schadenmeldung.helmsauer-gruppe.de/api/v1/login HTTP/1.1
content-type: application/json

{
    "user":"maxmustermann",
    "password":"ad45XV78?",
    "gruppe":"hk"
}

### change pw prod maxmustermann
POST https://schadenmeldung.helmsauer-gruppe.de/api/v1/password HTTP/1.1
content-type: application/json
authorization: 7e1eda74-9770-4a1b-9b9a-587ba11df3e8

{
    "oldPassword":"ad45XV78?",
    "newPassword":"7f59a154969f"
}

### change back pw prod maxmustermann
POST https://schadenmeldung.helmsauer-gruppe.de/api/v1/password HTTP/1.1
content-type: application/json
authorization: 7e1eda74-9770-4a1b-9b9a-587ba11df3e8

{
    "oldPassword":"7f59a154969f",
    "newPassword":"ad45XV78?"
}


##################### test #####################

### login testserver
POST https://testschadenmeldung.helmsauer-gruppe.de/api/v1/login HTTP/1.1
content-type: application/json

{
    "user":"Demokunde",
    "password":"Demo90443HK",
    "gruppe":"hk"
}

### login testserver maxmustermann
POST https://testschadenmeldung.helmsauer-gruppe.de/api/v1/login HTTP/1.1
content-type: application/json

{
    "user":"maxmustermann",
    "password":"ad45XV78?",
    "gruppe":"hk"
}

### change pw testserver maxmustermann
POST https://testschadenmeldung.helmsauer-gruppe.de/api/v1/password HTTP/1.1
content-type: application/json
authorization: 3f09cfd9-3529-4a09-98ec-ffa0421818c4

{
    "oldPassword":"ad45XV78?",
    "newPassword":"7f59a154969f"
}

### change back pw testserver maxmustermann
POST https://testschadenmeldung.helmsauer-gruppe.de/api/v1/password HTTP/1.1
content-type: application/json
authorization: 3f09cfd9-3529-4a09-98ec-ffa0421818c4

{
    "oldPassword":"7f59a154969f",
    "newPassword":"ad45XV78?"
}

### verträge testserver demo

GET https://testschadenmeldung.helmsauer-gruppe.de/api/v1/verträge HTTP/1.1
content-type: application/json
authorization: 613fa513-32a1-4671-8d91-59e6779912d4

### verträge testserver maxmustermann

GET https://testschadenmeldung.helmsauer-gruppe.de/api/v1/verträge HTTP/1.1
content-type: application/json
authorization: 3f09cfd9-3529-4a09-98ec-ffa0421818c4

### fremdverträge testserver

POST https://testschadenmeldung.helmsauer-gruppe.de/api/v1/fremdverträge/ HTTP/1.1
content-type: application/json
authorization: 613fa513-32a1-4671-8d91-59e6779912d4

{
    "files":{}
}

### message testserver

POST https://testschadenmeldung.helmsauer-gruppe.de/api/v1/message HTTP/1.1
content-type: application/json
authorization: 613fa513-32a1-4671-8d91-59e6779912d4

{
    "text":"blub",
    "files":{}
}

### pw request testserver
POST https://testschadenmeldung.helmsauer-gruppe.de/api/v1/remind HTTP/1.1
content-type: application/json
authorization: 613fa513-32a1-4671-8d91-59e6779912d4
client-version: 1.7.2

{
    "nachname": "Mustermann",
    "vorname": "Erika",
    "adresse": "Musterstraße"
}

################ Test Monitoring ################

### Stats
GET https://testschadenmeldung.helmsauer-gruppe.de/api/v1/admin/stats HTTP/1.1
content-type: application/json
authorization: 6ac06fc6-285e-4e39-8df8-14d7373fe4a8

################### Test Admin ###################

### Users
GET https://testschadenmeldung.helmsauer-gruppe.de/api/v1/admin/user HTTP/1.1
content-type: application/json
authorization: 6ac06fc6-285e-4e39-8df8-14d7373fe4a8

### Add User
POST https://testschadenmeldung.helmsauer-gruppe.de/api/v1/admin/user HTTP/1.1
content-type: application/json
authorization: 6ac06fc6-285e-4e39-8df8-14d7373fe4a8

{
    "name":"test",
    "password":"123",
    "mainname":"Demokunde",
    "gruppe":"hk",
    "mainPassword":"Demo90443HK"
}

### Change User
PUT https://testschadenmeldung.helmsauer-gruppe.de/api/v1/admin/user/test HTTP/1.1
content-type: application/json
authorization: 6ac06fc6-285e-4e39-8df8-14d7373fe4a8

{
    "name":"test",
    "password":"123",
    "mainname":"Demokunde",
    "gruppe":"hk",
    "mainPassword":"Demo90443HK"
}

### Remove User
DELETE  https://testschadenmeldung.helmsauer-gruppe.de/api/v1/admin/user/test2 HTTP/1.1
content-type: application/json
authorization: 6ac06fc6-285e-4e39-8df8-14d7373fe4a8


### Vertrag
GET  https://testschadenmeldung.helmsauer-gruppe.de/api/v1/admin/user/test/vertrag HTTP/1.1
content-type: application/json
authorization: 6ac06fc6-285e-4e39-8df8-14d7373fe4a8

### Change Verträge
PUT  https://testschadenmeldung.helmsauer-gruppe.de/api/v1/admin/user/test/vertrag HTTP/1.1
content-type: application/json
authorization: 6ac06fc6-285e-4e39-8df8-14d7373fe4a8

["VER20140626092811P76"]

##################### local #####################

### login
POST http://localhost:8080/api/v1/login HTTP/1.1
content-type: application/json

{
    "user":"Demokunde",
    "password":"Demo90443HK",
    "gruppe":"hk"
}

### login local maxmustermann
POST http://localhost:8080/api/v1/login HTTP/1.1
content-type: application/json

{
    "user":"mariamustermann",
    "password":"!Start1234!",
    "gruppe":"sue"
}

### change pw local maxmustermann
POST http://localhost:8080/api/v1/password HTTP/1.1
content-type: application/json
authorization: a6b58f4d-9a3c-47c4-97e6-028e961aa159

{
    "oldPassword":"!Start1234!",
    "newPassword":"7f59a154969f"
}

### change back pw local maxmustermann
POST http://localhost:8080/api/v1/password HTTP/1.1
content-type: application/json
authorization: a6b58f4d-9a3c-47c4-97e6-028e961aa159

{
    "oldPassword":"7f59a154969f+ieee",
    "newPassword":"!Start1234!"
}


### verträge
GET http://localhost:8080/api/v1/verträge HTTP/1.1
content-type: application/json
authorization: 69399023-62e2-4a60-9949-6f0fbd6bd3b6

### Dokument
GET http://localhost:8080/api/v1/adressen/AD_201406170853335LI/dokumente/DOK20140703114017KSI HTTP/1.1
content-type: application/json
authorization: 69399023-62e2-4a60-9949-6f0fbd6bd3b6

### Stats
GET http://localhost:8080/api/v1/stats HTTP/1.1
content-type: application/json
authorization: 6ac06fc6-285e-4e39-8df8-14d7373fe4a8
